package com.tooltwist.xdata.test;

public class TestData {

	public static String country_state_city_json = ""
		+ "{ \"data\" : {\n"
		+ "  \"description\" : \"Description\",\n"
		+ "  \"descriptionAltLang\" : \"Ze description\",\n"
		+ "  \"false\" : false,\n"
		+ "  \"null\" : null,\n"
		+ "  \"true\" : true,\n"
		+ "  \"zero\" : 0,\n"
		+ "  \"number\" : 12345,\n"
		+ "  \"negative\" : -321,\n"
		+ "  \"float\" : 123.456,\n"
		+ "  \"huge\" : 123.456e789,\n"
		+ "  \"miniscule\" : 123.456e-789,\n"
		+ "  \"country\" :\n"
		+ "  [\n"
		+ "    {\n"
		+ "      \"name\" : \"Australia\",\n"
		+ "      \"state\":\n"
		+ "      [\n"
		+ "        {\n"
		+ "          \"abbreviation\" : \"NSW\",\n"
		+ "          \"name\" : \"New South Wales\",\n"
		+ "          \"city\": [ \"Sydney\", \"Wollongong\", \"Newcastle\", \"Dubbo\" ]\n"
		+ "        },\n"
		+ "        {\n"
		+ "          \"abbreviation\" : \"VIC\",\n"
		+ "          \"name\" : \"Victoria\",\n"
		+ "          \"city\" : [ \"Melbourne\", \"Wodonga\", \"Dandenong\", \"Wangaratta\" ]\n"
		+ "        }\n"
		+ "      ]\n" // end states
		+ "    },\n"
		+ "    {\n"
		+ "      \"name\" : \"New Zealand\",\n"
		+ "      \"state\":\n"
		+ "      [\n"
		+ "        {\n"
		+ "          \"abbreviation\" : \"NI\",\n"
		+ "          \"name\" : \"North Island\",\n"
		+ "          \"city\" : [ \"Auckland\", \"Wellington\" ]\n"
		+ "        },\n"
		+ "        {\n"
		+ "          \"abbreviation\" : \"SI\",\n"
		+ "          \"name\" : \"South Island\",\n"
		+ "          \"city\" : [ \"Christchurch\", \"Queenstown\" ]\n"
		+ "        }\n"
		+ "      ]\n" // end states
		+ "    }\n"
		+ "  ]\n" // end countries
		+ " }"
		+ "}";
	
	
	public static String country_state_city_xml = ""
		+ "<data>"
		+ "  <description>Description</description>"
		+ "  <descriptionAltLang>Ze description</descriptionAltLang>"
		+ "  <false>false</false>"
		+ "  <null>null</null>"
		+ "  <true>true</true>"
		+ "  <zero>0</zero>"
		+ "  <number>12345</number>"
		+ "  <negative>-321</negative>"
		+ "  <float>123.456</float>"
		+ "  <huge>123.456e789</huge>"
		+ "  <miniscule>123.456e-789</miniscule>"
		+ "  <country>"
		+ "    <name>Australia</name>"
		+ "    <state>"
		+ "      <abbreviation>NSW</abbreviation>"
		+ "      <name>New South Wales</name>"
		+ "      <city>Sydney</city>"
		+ "      <city>Wollongong</city>"
		+ "      <city>Newcastle</city>"
		+ "      <city>Dubbo</city>"
		+ "    </state>"
		+ "    <state>"
		+ "      <abbreviation>VIC</abbreviation>"
		+ "      <name>Victoria</name>"
		+ "      <city>Melbourne</city>"
		+ "      <city>Wodonga</city>"
		+ "      <city>Dandenong</city>"
		+ "      <city>Wangaratta</city>"
		+ "    </state>"
		+ "  </country>"
		+ "  <country>"
		+ "    <name>New Zealand</name>"
		+ "    <state>"
		+ "      <abbreviation>NI</abbreviation>"
		+ "      <name>North Island</name>"
		+ "      <city>Auckland</city>"
		+ "      <city>Wellington</city>"
		+ "    </state>"
		+ "    <state>"
		+ "      <abbreviation>SI</abbreviation>"
		+ "      <name>South Island</name>"
		+ "      <city>Christchurch</city>"
		+ "      <city>Queenstown</city>"
		+ "    </state>"
		+ "  </country>"
		+ "</data>";

}
